### ISSUE TITLE
Реализовать запись примитивов в файл и считывание их из файла

### ISSUE THREAD

**Issue by dkappdev** [PMPU19B13/Introduction-to-Programming-spring-2020#14]

**Comment by kolbacer** [comment]
-добавил reader.h и reader.cpp

в controller:
-перегрузил updateView() для вывода в файл
-добавил readPrimitive() (считывает 1 строку)
-добавил updateMemory() (полностью считывает файл)

в drawer:
-перегрузил drawPrimitive для вывода в файл

пример работы:

main.cpp
![image](https://user-images.githubusercontent.com/61326288/76710644-3be69800-671a-11ea-8770-e81d6130f169.png)
ввод
![image](https://user-images.githubusercontent.com/61326288/76710657-633d6500-671a-11ea-84f7-ec3cf9d7a515.png)
вывод
![image](https://user-images.githubusercontent.com/61326288/76710664-75b79e80-671a-11ea-8f4b-24ec3fcc6612.png)
